/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class phoenix3d_px2_library_PX2Natives */

#ifndef _Included_phoenix3d_px2_library_PX2Natives
#define _Included_phoenix3d_px2_library_PX2Natives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeOdle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeOdle
  (JNIEnv *, jclass);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeInit
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeOnPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeOnPause
  (JNIEnv *, jclass);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeOnResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeOnResume
  (JNIEnv *, jclass);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeOnTerm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeOnTerm
  (JNIEnv *, jclass);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeSetResourcePath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeSetResourcePath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeSetDataUpdateServerType
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeSetDataUpdateServerType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeTouchPressed
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeTouchPressed
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeTouchReleased
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeTouchReleased
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeTouchMoved
 * Signature: ([I[F[F)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeTouchMoved
  (JNIEnv *, jclass, jintArray, jfloatArray, jfloatArray);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeTouchCancelled
 * Signature: ([I[F[F)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeTouchCancelled
  (JNIEnv *, jclass, jintArray, jfloatArray, jfloatArray);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeKeyDown
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeKeyDown
  (JNIEnv *, jclass, jint);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeInsertText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeInsertText
  (JNIEnv *, jclass, jstring);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeDeleteBackward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeDeleteBackward
  (JNIEnv *, jclass);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeGetContentText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeGetContentText
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
