/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class phoenix3d_px2_thirdplatform_PX2TPNatives */

#ifndef _Included_phoenix3d_px2_thirdplatform_PX2TPNatives
#define _Included_phoenix3d_px2_thirdplatform_PX2TPNatives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     phoenix3d_px2_thirdplatform_PX2TPNatives
 * Method:    SetPX2ThirdPlatform
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_thirdplatform_PX2TPNatives_SetPX2ThirdPlatform
  (JNIEnv *, jclass, jstring);

/*
 * Class:     phoenix3d_px2_thirdplatform_PX2TPNatives
 * Method:    OnLoginSuc
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_thirdplatform_PX2TPNatives_OnLoginSuc
  (JNIEnv *, jclass, jint, jstring, jstring, jstring);

/*
 * Class:     phoenix3d_px2_thirdplatform_PX2TPNatives
 * Method:    OnLoginCancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_thirdplatform_PX2TPNatives_OnLoginCancel
  (JNIEnv *, jclass);

/*
 * Class:     phoenix3d_px2_thirdplatform_PX2TPNatives
 * Method:    OnLoginFailed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_thirdplatform_PX2TPNatives_OnLoginFailed
  (JNIEnv *, jclass);

/*
 * Class:     phoenix3d_px2_thirdplatform_PX2TPNatives
 * Method:    OnGuestOfficialSuc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_thirdplatform_PX2TPNatives_OnGuestOfficialSuc
  (JNIEnv *, jclass);

/*
 * Class:     phoenix3d_px2_thirdplatform_PX2TPNatives
 * Method:    OnPaySuc
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_thirdplatform_PX2TPNatives_OnPaySuc
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     phoenix3d_px2_thirdplatform_PX2TPNatives
 * Method:    OnPayCancel
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_thirdplatform_PX2TPNatives_OnPayCancel
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     phoenix3d_px2_thirdplatform_PX2TPNatives
 * Method:    OnPayFailed
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_thirdplatform_PX2TPNatives_OnPayFailed
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     phoenix3d_px2_thirdplatform_PX2TPNatives
 * Method:    OnPaySMSSent
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_thirdplatform_PX2TPNatives_OnPaySMSSent
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     phoenix3d_px2_thirdplatform_PX2TPNatives
 * Method:    OnPayRequestSubmitted
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_thirdplatform_PX2TPNatives_OnPayRequestSubmitted
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     phoenix3d_px2_thirdplatform_PX2TPNatives
 * Method:    OnPayError
 * Signature: (Ljava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_thirdplatform_PX2TPNatives_OnPayError
  (JNIEnv *, jclass, jstring, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
