/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_appplay_platformsdk_PlatformCPPNative */

#ifndef _Included_org_appplay_platformsdk_PlatformCPPNative
#define _Included_org_appplay_platformsdk_PlatformCPPNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_appplay_platformsdk_PlatformCPPNative
 * Method:    SetPlatformSDK
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_appplay_platformsdk_PlatformCPPNative_SetPlatformSDK
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_appplay_platformsdk_PlatformCPPNative
 * Method:    OnLoginSuc
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_appplay_platformsdk_PlatformCPPNative_OnLoginSuc
  (JNIEnv *, jclass, jint, jstring, jstring, jstring);

/*
 * Class:     org_appplay_platformsdk_PlatformCPPNative
 * Method:    OnLoginCancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_appplay_platformsdk_PlatformCPPNative_OnLoginCancel
  (JNIEnv *, jclass);

/*
 * Class:     org_appplay_platformsdk_PlatformCPPNative
 * Method:    OnLoginFailed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_appplay_platformsdk_PlatformCPPNative_OnLoginFailed
  (JNIEnv *, jclass);

/*
 * Class:     org_appplay_platformsdk_PlatformCPPNative
 * Method:    OnGuestOfficialSuc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_appplay_platformsdk_PlatformCPPNative_OnGuestOfficialSuc
  (JNIEnv *, jclass);

/*
 * Class:     org_appplay_platformsdk_PlatformCPPNative
 * Method:    OnPaySuc
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_appplay_platformsdk_PlatformCPPNative_OnPaySuc
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     org_appplay_platformsdk_PlatformCPPNative
 * Method:    OnPayCancel
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_appplay_platformsdk_PlatformCPPNative_OnPayCancel
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     org_appplay_platformsdk_PlatformCPPNative
 * Method:    OnPayFailed
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_appplay_platformsdk_PlatformCPPNative_OnPayFailed
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     org_appplay_platformsdk_PlatformCPPNative
 * Method:    OnPaySMSSent
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_appplay_platformsdk_PlatformCPPNative_OnPaySMSSent
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     org_appplay_platformsdk_PlatformCPPNative
 * Method:    OnPayRequestSubmitted
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_appplay_platformsdk_PlatformCPPNative_OnPayRequestSubmitted
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     org_appplay_platformsdk_PlatformCPPNative
 * Method:    OnPayError
 * Signature: (Ljava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_org_appplay_platformsdk_PlatformCPPNative_OnPayError
  (JNIEnv *, jclass, jstring, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
